project:
  type: website  
  output-dir: docs


website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: CELP-Lab
      - text: Members
        menu:
          - href: current_members.qmd
            text: Current Members
          - href: lab_alums.qmd
            text: Lab Alums
      - href: research.qmd
        text: Research
      - href: pubs.qmd
        text: Publications
      - href: resources.qmd
        text: Data & Code
      - href: prospectives.qmd
        text: Prospective Students
      - href: undergrad_resources.qmd
        text: Resources for Undergraduates
    right:
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/jebyrnes.bsky.social/lists/3laooalcpjz2c

  page-footer: 
    left: '[![](/images/New_UMB_Logo_news_042522.jpg){width="70%"}](https://www.umb.edu/)'
    right: 'Made with {{< fa brands r-project size=2x >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" height=20px}](https://quarto.org/) <br>
      Code at {{< fa brands github>}}<br>'
      
format:
  html:
    mainfont: Avenir
    css: styles.css
    toc: true


