---
title: "Prospective Students"
page-layout: article
---
<p>Thanks for your interest in joining the Byrnes lab! I am currently interested ina PhD student interested in kelp forest community ecology and/or ocean data science. I am  looking for  students at the moment.</p>

<p align="justify">Graduate school is a fantastic intellectual adventure that can lead you into a lot of different directions. What you get out of it will be directly proportional to what you put in. You want to make sure you chose the right mentor who can guide you in asking research questions that will push the boundaries of science. Before contacting me, you should get to know the kinds of work that we do here in my lab.</p>

<p align="justify">As for working with me, I love mentoring students. It's a large investment for me, and with every student turn them into first-rate scientists. And by scientist I mean someone who excels in critical thinking, always keeps an eye on the big picture of understanding nature, possesses excellent written and oral communication, can engage with peers in the ivory tower or someone at a public stakeholder meeting or science cafe, likes to learn how to code elegant and novel analyses, and can figure out how to MacGyver up any field sampling gear that they might need at a moments notice. It's a partnership, and one where I hope we'll learn a lot from each other.</p>

<p><span id="subtitle"><b>Why my lab?</b></span></p>
<p align="justify">My lab focuses on asking questions about marine community ecology, the consequences of modern day species loss, climate change, food web network topology, new statistical approaches to ecology &amp; Big Data, and more.</p>

<p align="justify">I'm looking for students who have a love of thinking about Ecology with an eye to the big picture. We employ an approach that brings together intensive fieldwork with equally intensive quantitative analysis. Equally interested in being soaking wet in the field or hacking away at a piece of computer code? This may be the lab for you. Currently, I'm interested in kelp forests, salt marshes, and fouling communities in and around New England. But I'm open to students wanting to work in any system provided it's the right system for an exciting research question. Our lab also has a strong commitment to outreach, engagement, and science education.</p>

<p><span id="subtitle"><b>Why Umass Boston?</b></span></p>
<p align="justify">UMass Boston is a great place to cut your teeth as a marine ecologist. The <a href="http://www.umb.edu/academics/csm/biology/">Biology Department</a> at UMB is broad with expertise in a variety of fields within biology. You'll have to interact with people working on very different systems and questions than you, which will keep you nimble and thinking big. Not only that, but you'll be able to collaborate with colleagues in the <a href="http://www.umb.edu/academics/environment">School for the Environment</a></p> 

<p align="justify">We're right at the southern end of the Gulf of Maine with access to field sites such as Salem Sound via the <a href="http://www.salemstate.edu/academics/schools/1028.php">Cat Cove Marine Lab</a>, the Boston Harbor Islands, our <a href="http://www.umb.edu/nantucket/">Nantucket Field Station</a>, the marshes of the<a href="http://ecosystems.mbl.edu/pie/">Plum Island Ecosystem LTER</a>, the <a href="http://www.wellsreserve.org/">Wells National Estuarine Research Reserve</a>, the rocky intertidal and subtidal of the <a href="http://sml.cornell.edu">Shoals Marine Lab</a>, the <a href="http://www.northeastern.edu/marinescience/">Marine Science Center</a>, and much more. Working around Boston, you have the opportunity to look at the ecology of the oceans in an urban setting and then compare that to more remote locations north and south. Last, the questions you can ask here have direct relevance to conservation and management in New England. You cannot understand the oceans here without thinking of their long history and future destiny of human use.</p>

<p>Also, the diving is fantastic.</p>

<p><span id="subtitle"><b>Masters or PhD?</b></span><br />
I get this question a lot, so I thought I'd give my take on it.</p>
<p>Before answering that, ask yourself, why are you interested in a graduate degree? Think about it. Take a second. I'll wait.</p>
<p>...</p>
<p>...</p>
<p>OK, here's my answer. Your milage may vary. If you have no research experience aside from working as a lab tech, a masters degree might be what you're looking for. Or if you don't know if you want to pursue a long-term independent research program, or want to try a particular system or question out, it's a great way to walk down that road for a little while. Or it's excellent as there are a <a href="http://www.pdx.edu/careers/what-can-i-do-with-a-degree-in-environmental-studiesenvironmental-sciences">wide variety of career options</a> that are open to you with a masters. Do some homework - ask yourself how this degree will help you achieve your professional goals.</p>
<p>For a PhD, I will expect that you have some independent research experience under your belt. This doesn't mean you need a masters (I didn't have one when I started my PhD!). This could be an REU, an undergraduate independent thesis, or time spent as a technician designing and executing a research project. Either way, you should have run a full research project from conception to execution to writing it up. Why? A few things. First, as a PhD, I expect you to come in already having the ability to ask big questions and have some self-confidence in your ability to tackle them. You learn a lot about how to ask and answer a scientific question by, well, asking and answering a question! Second, a 5-7 year commitment is a lot. I want you to know what you're getting into before you start the program. Original research is process that is in equal measures incredibly rewarding and incredibly difficult. It is something to engage in with abandon, or not at all. You should know what you're getting into before you start.</p>

<p><span id="subtitle"><b>The application process</b></span><br />
If, after we talk, you're planning on applying, there are two programs you can apply through. I accept students through both the <a href="http://www.umb.edu/academics/csm/biology/grad">Department of Biology grad program</a> and the <a href="http://www.umb.edu/academics/environment/grad">School for the Environment grad program</a> at UMB. I take students through both programs, but both are different. To be brief, Biology as more of a straight science-only focus. SFE students will likely have more of an applied angle to their work.  Either way, **talk to me about which program is right for you before applying**, and note that they may have different deadlines in any given year. See the pages above for all of the information you need.</p>

<p align="justify">Is this the right lab for you? Hopefully the above gave you some ideas. But, before you contact me, please go back and take a look at <a href="http://byrneslab.net">some of my listed research areas</a>. Broadly, I'm interested in marine community ecology, climate change, kelp forests, urban ecology, and the consequences of modern day extinctions. In my lab, we try and couple intensive fieldwork with a heavily quantitative way of thinking about the world. We code a lot! Sound like you, or who you would like to become? Great, go check out some of my lab's <a href="http://byrneslab.net/publications/">publications</a>. See if something catches your interest. I'm always exploring new ideas, but if you want to know where the lab might be going, there's no better way than to see where it has been.</p>

<p>For folk interested in a masters, definitely look at what is ongoing, and think about ways that you can use those areas as a jumping off point. A masters is shorter, and so my goal for you is to help you get you up and running with a project pronto - sometimes even slotting you into pre-existing projects.</p> 

<p align="justify">For potential PhD candidates, think bigger. What question is burning a whole in your brain? How do you want to fundamentally advance our understanding of the world? If you cannot answer these questions, at least vaguely, please think about why you want to pursue this degree.</p>

<p><span id="subtitle">Contacting Me</span></p>
<p align="justify">After that rigamarole, if you are interested in pursing graduate or postdoctoral research with me, please email me with a brief introduction, including some info about your research and academic experience. Let me know what your research interests are, and what you see as your professional goals. Please also include a copy of your CV and a transcript (this can be informal - I want to know what courses you've taken). Also, if you have any particular culinary talents, let me know. This is important not just to me, but definitely to my current students.</p>
<p><!-- <span id=subtitle><b>Why a graduate degree?</b>


<p align="justify">
Why are you interested in a graduate degree?   For a PhD, I know the default answer is always "So I can be a university professor."  That's great, and I look forward to working together to help you achieve that goal.  Do some reading, though, and make sure you know <a href="http://contemplativemammoth.wordpress.com/2013/06/19/academia-doesnt-have-a-phd-problem-it-has-an-attitude-problem/">what you're jumping into</a>.  The job market for academics is <a href="http://www2.esm.vt.edu/~jjsocha/socha_lab/Opportunities_files/science_crisis_article.pdf">never great</a>.  This is not to discourage you, but take a breath before diving in and think about long-term goals.  Know also that a PhD is amazing training for a <a href="http://dynamicecology.wordpress.com/2013/06/12/advice-finding-a-career-in-non-academic-research-guest-post/">wide variety</a> of <a href="http://storify.com/jebyrnes/nonacademiccareers">careers</a> as well. So, think about your long-term goals and why a PhD is the right road for you. You may also be interested in checking out <a href="http://www.amazon.com/Guide-Academia-Surviving-Postdocs-Research/dp/0470960418">this book</a>.

--></p>
<p></span></p>